# Generated by Django 4.2.6 on 2023-10-21 22:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("theatre", "0002_actor_alter_theatrehall_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=63)),
            ],
        ),
    ]
