# Generated by Django 4.2.6 on 2023-10-23 15:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("theatre", "0008_alter_performance_options_alter_performance_play_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="play",
            options={"ordering": ["title"]},
        ),
        migrations.AlterField(
            model_name="genre",
            name="name",
            field=models.CharField(max_length=63, unique=True),
        ),
    ]
